export const styles = {
  page: {
    minHeight: '100vh',
    background: '#f8f9fa',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Noto Sans Thai', sans-serif",
  } as React.CSSProperties,
  header: {
    background: '#fff',
    padding: '14px 32px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } as React.CSSProperties,
  logo: {
    fontSize: '20px',
    fontWeight: 800,
    color: '#00A651',
    letterSpacing: '-0.5px',
  } as React.CSSProperties,
  card: {
    background: '#fff',
    border: '1px solid #e9ecef',
    borderRadius: '8px',
    padding: '24px',
    marginBottom: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  } as React.CSSProperties,
  cardTitle: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#343a40',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: '1px solid #f1f3f5',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #dee2e6',
    borderRadius: '4px',
    fontSize: '13px',
    outline: 'none',
    transition: 'border-color 0.2s',
  } as React.CSSProperties,
  inputFocus: {
    borderColor: '#00A651',
  } as React.CSSProperties,
  select: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #dee2e6',
    borderRadius: '4px',
    fontSize: '13px',
    outline: 'none',
    background: '#fff',
    cursor: 'pointer',
  } as React.CSSProperties,
  label: {
    fontSize: '12px',
    fontWeight: 500,
    color: '#495057',
    marginBottom: '4px',
    display: 'block',
  } as React.CSSProperties,
  btnPrimary: {
    padding: '10px 20px',
    background: '#00A651',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background 0.2s',
  } as React.CSSProperties,
  btnSecondary: {
    padding: '10px 20px',
    background: '#fff',
    color: '#495057',
    border: '1px solid #dee2e6',
    borderRadius: '4px',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'background 0.2s',
  } as React.CSSProperties,
  btnDanger: {
    padding: '10px 20px',
    background: '#e03131',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
  } as React.CSSProperties,
  badge: {
    padding: '3px 10px',
    borderRadius: '100px',
    fontSize: '11px',
    fontWeight: 500,
    display: 'inline-block',
  } as React.CSSProperties,
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  } as React.CSSProperties,
  grid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '16px',
  } as React.CSSProperties,
  container: {
    maxWidth: '720px',
    margin: '0 auto',
    padding: '32px 24px',
  } as React.CSSProperties,
  containerWide: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '32px 24px',
  } as React.CSSProperties,
  alert: {
    padding: '12px 16px',
    borderRadius: '6px',
    fontSize: '13px',
    marginBottom: '16px',
  } as React.CSSProperties,
  alertWarning: {
    background: '#fff3cd',
    border: '1px solid #ffc107',
    color: '#856404',
  } as React.CSSProperties,
  alertSuccess: {
    background: '#d4edda',
    border: '1px solid #28a745',
    color: '#155724',
  } as React.CSSProperties,
  uploadZone: {
    border: '2px dashed #dee2e6',
    borderRadius: '8px',
    padding: '24px',
    textAlign: 'center' as const,
    cursor: 'pointer',
    transition: 'border-color 0.2s, background 0.2s',
    background: '#f8f9fa',
  } as React.CSSProperties,
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '13px',
  } as React.CSSProperties,
  th: {
    padding: '10px 12px',
    textAlign: 'left' as const,
    fontWeight: 600,
    color: '#495057',
    borderBottom: '2px solid #e9ecef',
    fontSize: '12px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  } as React.CSSProperties,
  td: {
    padding: '12px',
    borderBottom: '1px solid #f1f3f5',
    color: '#343a40',
  } as React.CSSProperties,
  trHover: {
    background: '#f8f9fa',
  } as React.CSSProperties,
  fieldGroup: {
    marginBottom: '16px',
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#343a40',
    marginBottom: '8px',
  } as React.CSSProperties,
  textMuted: {
    fontSize: '12px',
    color: '#868e96',
  } as React.CSSProperties,
  flexBetween: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  } as React.CSSProperties,
  flexCenter: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  } as React.CSSProperties,
  flexGap: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  } as React.CSSProperties,
};

export const badgeColors: Record<string, React.CSSProperties> = {
  pending: { background: '#fff3cd', color: '#856404' },
  in_review: { background: '#cce5ff', color: '#004085' },
  approved: { background: '#d4edda', color: '#155724' },
  rejected: { background: '#f8d7da', color: '#721c24' },
  completed: { background: '#e6f7ef', color: '#008542' },
  draft: { background: '#f1f3f5', color: '#495057' },
};

export const statusLabels: Record<string, string> = {
  pending: 'รอดำเนินการ',
  in_review: 'กำลังตรวจสอบ',
  approved: 'อนุมัติแล้ว',
  rejected: 'ไม่อนุมัติ',
  completed: 'เสร็จสิ้น',
  draft: 'แบบร่าง',
};
